name: CI

on = "schedule(*/1 * * * *)"
#on:
  #push:
  #  branches: [ master ]
  #schedule:
    - cron  '*/1 * * * *'    

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          VERSION=$(date +%s)
          docker build . --file Dockerfile --tag lukaszciechanowicz/marianb0t:${VERSION}
          docker run -e TWITTER_CONSUMER_KEY=${{ secrets.TWITTER_CONSUMER_KEY }} -e TWITTER_CONSUMER_SECRET=${{ secrets.TWITTER_CONSUMER_SECRET }} -e TWITTER_ACCESS_TOKEN_KEY=${{ secrets.TWITTER_ACCESS_TOKEN_KEY }} -e TWITTER_ACCESS_TOKEN_SECRET=${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} lukaszciechanowicz/marianb0t:${VERSION}
